name: "Dozzle Agent"
slug: "dozzle_agent"
description: "Dozzle Agent"
version: "1.0.3"
url: "https://dozzle.dev/guide/agent"
arch:
  - amd64

startup: services
init: false

docker_api: true

ports:
  7007/tcp: 7007
ports_description:
  7007/tcp: "Dozzle agent endpoint"

environment:
  DOZZLE_HOSTNAME: home-assistant
  DOCKER_HOST: "unix:///run/docker.sock"
