name: "Nginx Proxy Manager"
slug: "nginx_proxy_manager"
description: "Nginx Proxy Manager"
version: "1.2.0"
url: "https://nginxproxymanager.com/"
arch:
  - amd64

startup: services
init: false

ports:
  81/tcp: null
  443/tcp: null
  1882/tcp: null

ports_description:
  81/tcp: "Management port"
  443/tcp: "HTTPS port"
  1882/tcp: "Streams port"

map:
  - type: ssl
    read_only: false
    path: /etc/letsencrypt

environment:
  TZ: "Europe/London"
